
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrexcsswuedtdjiscosl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyZXhjc3N3dWVkdGRqaXNjb3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzA5MzMsImV4cCI6MjA2MTg0NjkzM30.QAOv3qBZ6WdOyLwUh8uIZwl4xht66IO4YimuwApMd_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
